name = "SpeexDSPBuilder"
uuid = "c24bc66c-1bef-11e9-0b46-cd960f00bdbb"
authors = ["YuK_Ota <whitenightwinter@gmail.com>"]
version = "0.1.0"

[deps]
BinaryBuilder = "12aac903-9f7c-5d81-afc2-d9565ea332ae"
